### ISSUE TITLE
External Html file is not closed

### ISSUE THREAD

**Issue by erikvanoosten** [sparsetech/pine#39]
`scala.ui.Source.fromFile` does not automatically close the underlying file. You have to call `close` explicitly. This is not done in `ExternalHtml`. e.g. here: https://github.com/sparsetech/pine/blob/284b857d0d0233966d2793d9c30e07a9434d724d/shared/src/main/scala/pine/macros/ExternalHtml.scala#L35

**Comment by tindzk** [comment]
Thanks for the report! I will fix it.

**Comment by erikvanoosten** [comment]
There is another one in `project/MDNParser.scala`.

**Comment by tindzk** [comment]
Good catch. I corrected it as well.
