### ISSUE TITLE
Allow reading html from path relative to code being compiled

### ISSUE THREAD

**Issue by erikvanoosten** [sparsetech/pine#40]
The `html("page.html")` finds the html file relative to the current working directory (cwd) of the compiler. This is brittle. I am using Intellij; I see that by default it uses a different cwd then sbt.

I am currently modeling components that have a scala file and an html file. It would like to keep them together in the same directory. It would be great if code in the scala file can read the html file relative to the code being compiled.

**Comment by tindzk** [comment]
Yes, this is certainly possible, but for larger websites the current behaviour seems more adequate. I usually store all HTML files in `<projectRoot>/assets/html`, separately from the source code. This works well with sbt-assembly if you set the following option:

```scala
 reStart / baseDirectory := file(".")
```

You could add a flag to change the resolution behaviour of `html` on a per-case basis.
