### ISSUE TITLE
Interpolation for attributes fails when concatenating

### ISSUE THREAD

**Issue by erikvanoosten** [sparsetech/pine#41]
Interpolation for attributes in html literals does not work as expected when the `$` expression is not the entire attribute value.

For example the following fragment:

```scala
val rowId = "abc"
html"""<div id="row-${rowId}"></div>"""
```

produces: `<div id="row-${0}"></div>` instead of the expected `<div id="row-abc"></div>`.

**Comment by erikvanoosten** [comment]
Work arounds:

1. first instantiate a variable:

```scala
val rowId = "abc"
val rowIdAttribute = s"row-$rowId"
html"""<div id="row-${rowId}"></div>"""
```

2. use an expression in the interpolation:

```scala
val rowId = "abc"
html"""<div id="${s"row-$rowId"}"></div>"""
```

**Comment by tindzk** [comment]
Thanks for the bug report! This was actually fixed a couple of days ago (see [commit](https://github.com/sparsetech/pine/commit/ecd3b9608a8e2ef92d2d5af6a076948585fb7a05)).
