### ISSUE TITLE
Add `TagRef.exists()`

### ISSUE THREAD

**Issue by erikvanoosten** [sparsetech/pine#43]
A feature request: it would be nice if `TagRef.ById` has a method to find out whether the tag exists.

For example by adding the method `exists`. Another option would be to leverage `each` and let it return an `Option`. Or make it more transparent by adding something like `TagRef[tag.Div].optional("divId")`.

**Comment by tindzk** [comment]
Thanks! This is a good idea. I am thinking about changing it as follows:

```scala
TagRef.ByTag[tag.A].dom: dom.html.Anchor
TagRef.ByTag[tag.A].opt.dom: Option[dom.html.Anchor]
TagRef.ByTag[tag.A].each.dom: List[dom.html.Anchor]  // Currently domAll
```

`each` should only be available for `ByTag` and `ByClass`.

If we return an `Option`, you could call `nonEmpty` to check for a node's existence in the DOM and also leverage other combinators such as `filter`, `exists` etc.

I have not tested it, but you might be able to use `Try(ref.dom).toOption.nonEmpty` as a workaround for now.
