### ISSUE TITLE
Readonly is a boolean attribute

### ISSUE THREAD

**Issue by erikvanoosten** [sparsetech/pine#44]
In 0.1 according to `HtmlHelper.BooleanAttributes` `readonly` is a boolean attribute. Unfortunately it is not defined as such in `Attributes` for `Input` and `TextArea`. One of these has to give, currently one can not dynamically set the attribute.

**Comment by erikvanoosten** [comment]
*Workaround*

Define the following:

```scala
  implicit class CorrectedTagRefAttributesInput(tagRef: TagRef[tag.Input]) {
    val readonly2 = new Attribute[tag.Input, Boolean, Boolean](tagRef, "readonly")
  }
```

and then set the attribute as follows:

```scala
  inputTagRef.readonly2 := true
```

**Comment by tindzk** [comment]
Thanks for the report! Support for boolean attributes has been improved in 8d04f44be42a42515ce899d7706b0a4040ab5664 and a394f211129d71806c1b43c5a189d7bdc41da5a5. Your issue should be covered by those two commits.

FYI I am planning to release a new version next week. Then you can get rid of all the workarounds.
