### ISSUE TITLE
`appendSibling`

### ISSUE THREAD

**Issue by erikvanoosten** [sparsetech/pine#45]
I was looking for a way to append a tag after another tag, e.g. `appendSibling` (and maybe also `prependSibling`). I found a workaround, but having these would have been great.

**Comment by tindzk** [comment]
Thanks for the request! Could you please provide examples how these functions would behave? A node only has access to its children, so I am not entirely sure whether it can be implemented.

**Comment by erikvanoosten** [comment]
Say you have the following:
```html
<ol>
   <li id="a1"></li>
   <li id="a3"></li>
   <li id="a4"></li>
</ol>
```

I would like to have a way to insert `<li id="a2"></li>` after the element with id `a1`, the result would be:
```html
<ol>
   <li id="a1"></li>
   <li id="a2"></li>
   <li id="a3"></li>
   <li id="a4"></li>
</ol>
```

If it is not possible to get the parent of a tag, I am also fine with an operation where you pass the parent and say something like `insertAfter(parentRef, a1Ref, html"""<li id="a2"></li>""")`.

**Comment by erikvanoosten** [comment]
Say you have the following:
```html
<ol>
   <li id="a1"></li>
   <li id="a3"></li>
   <li id="a4"></li>
</ol>
```

I would like to have a way to insert `<li id="a2"></li>` after the element with id `a1`, the result would be:
```html
<ol>
   <li id="a1"></li>
   <li id="a2"></li>
   <li id="a3"></li>
   <li id="a4"></li>
</ol>
```

If it is not possible to get the parent of a tag, I am also fine with an operation where you pass the parent and say something like `insertAfter(parentRef, a1Ref, html"""<li id="a2"></li>""")`.

**Comment by tindzk** [comment]
Thanks for the clarification! Recently, I needed a similar function and introduced `insertAt()` in https://github.com/sparsetech/pine/commit/dfba4944893850ae1a39dfaec89486aeb7b20b70. However, it takes a child index instead of a `TagRef`. I will investigate whether it is feasible to add `insertBefore` and `insertAfter` as per your suggestion. I am thinking about the following syntax:

```scala
parentRef.insertBefore(childRef, value)
parentRef.insertAfter(childRef, value)
```

It would only work if `parentRef` is a direct parent of `childRef`.

**Comment by erikvanoosten** [comment]
That looks really good. Thanks!
