### ISSUE TITLE
`TagTokenListAttribute.state` duplicates attribute values

### ISSUE THREAD

**Issue by erikvanoosten** [sparsetech/pine#46]
Say we have the following template (`d-none` is a Bootstrap class to hide something):
  `html"""<span id="err" class="d-none">Error message</span>"""`

Now the following code:
```
TagRef[tag.Span]("err").`state`.(true, "d-none")
```

Results in the following html: `<span id="err" class="d-none d-none">Error message</span>`

A following invocation to `state` with `false` will only remove the first `d-none` (`List.diff` in method `remove` only removes the first occurrence).

It is not clear to me if `TagTokenListAttribute` needs to support duplicate values. For the `class` attribute this is clearly not desirable but there might be other use cases I am not aware off.

**Comment by tindzk** [comment]
Thanks for pointing this out! This is a regression from the latest release.

According to the [specification](https://html.spec.whatwg.org/#space-separated-tokens), there are "space-separated tokens" and "comma-separated tokens", both of which are defined as sets.

Therefore, it would make sense to change `TagTokenListAttribute` to `TagTokenSetAttribute`.

**Comment by erikvanoosten** [comment]
Hi @tindzk , could you please release this?

**Comment by tindzk** [comment]
Yes, I will release it tomorrow. Sorry it took so long.
