### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by kevinwright** [sparsetech/pine#50]
README.md states Apache v2

But without a dedicated LICENSE file automated tools (including GIthub's own, under insights -> community) are unable to recognise this fact.

**Comment by tindzk** [comment]
Thanks for noticing! I added the missing licence file. Now it says:

![image](https://user-images.githubusercontent.com/196819/50730199-b3e52580-1147-11e9-8561-be560d03dfe2.png)
