### ISSUE TITLE
Scala Native support

### ISSUE THREAD

**Issue by david-bouyssie** [sparsetech/pine#58]
I'm trying to use Pine in a Scala Native project. I'm interested in the XML parsing feature.

I tried to use the internal HtmlParser like this:

```scala
 pine.internal.HtmlParser.fromString("""<item><link></link></item>""", xml = true)
```

but I get the following errors:

```
[error] cannot link: @pine.Node
[error] cannot link: @pine.Tag
[error] cannot link: @pine.Tag::attributes_scala.collection.immutable.Map
[error] cannot link: @pine.Tag::children_scala.collection.immutable.List
[error] cannot link: @pine.Tag::tagName_java.lang.String
[error] cannot link: @pine.internal.HtmlParser$
[error] cannot link: @pine.internal.HtmlParser$::fromString_java.lang.String_bool_pine.Tag
```

Is it an expected behavior?

Thanks

**Comment by tindzk** [comment]
Thanks for the report! This seems to be a regression in v0.1.5. Your example works fine with v0.1.4.

**Comment by david-bouyssie** [comment]
Thank you @tindzk, I switched to 0.1.4 and my codebase is now also working on SN.

Thank you very much for providing XML parsing in the SN world 😄 
This was really a missing piece of software!

BTW, don't you think that ```pine.XmlParser.fromString``` should also be available for SN builds?
It seems there is no such a shortcut.

**Comment by tindzk** [comment]
Great to hear you find it useful! While investigating the issue, I also noticed that `pine.XmlParser` was missing in Scala Native builds. The pull request #59 will fix this.

**Comment by david-bouyssie** [comment]
Awesome 👍
