### ISSUE TITLE
Pine Tag.toText  seems to not preserve line breaks

### ISSUE THREAD

**Issue by david-bouyssie** [sparsetech/pine#65]
I have some XML documents with specific nodes where I would like to preserve the line breaks in a round-trip process (deserializing and serializing later again).

For this I'm calling the  ```toText ``` methods on ```Tag[Singleton] objects```, but it gives me a String without preserving the line breaks.

Thurs I tried on a local fork to remove the ```.replaceAll("\\s+", " ")``` which is done in this file:
https://github.com/sparsetech/pine/blob/c4f7b15ab77a5ee3b46151cb1d8835796ac272f6/src/main/scala/pine/TagRender.scala

But I'm still not able to preserve line breaks.
Any suggestion ?

**Comment by tindzk** [comment]
`toText` is meant to be used on HTML documents only. It gives a textual representation of typical HTML elements, e.g. converting `<br/>` to `\n`.

You could get a node's text as follows:

```scala
val tree = pine.XmlParser.fromString("<node>\ntest</node>")

tree.children.collectFirst {
  case pine.Text(t) => t
}
```

We can add a helper function `textContent: Option[String]` on `Node` that will traverse the tree recursively and return the content of the first `Text` node it found. Then, the above can be shortened to `tree.textContent`.

**Comment by david-bouyssie** [comment]
Great! Thank you for your quick reply.
I tried your solution and it fixed my problem.
Have a shortcut would be indeed handy :)

**Comment by david-bouyssie** [comment]
Thanks 👏
